version: '3.9'
services:
  backend:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    env_file:
    - .env
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local
    